InFlight.defaults = {
	profile = {
		p = "BOTTOM",
		rp = "TOP",
		x = 0,
		y = -170,
		countup = true,
		fill = true,
		spark = true,
		texture = "Blizzard",
		width = 230,
		height = 14,
		border = "Blizzard Dialog",
		barcolor = { r = 0.5, g = 0.5, b = 0.8, a = 1.0, },
		unknowncolor = { r = 0.2, g = 0.2, b = 0.4, a = 1.0, },
		backcolor = { r = 0.1, g = 0.1, b = 0.1, a = 0.6, },
		bordercolor = { r = 0.6, g = 0.6, b = 0.6, a = 0.8, },
		inline = false,
		totext = "-->",
		font = "2002 Bold",
		fontsize = 12,
		fontcolor = { r = 1.0, g = 1.0, b = 1.0, a = 1.0, },
		outline = false,
		outlinetime = false,
		chatlog = true,
		confirmflight = false,
		perchar = false,
	},
	global = {
		["Horde"] = {
			["Crossroads"] = {
				["Bloodvenom Post"] = 253,
				["Sun Rock Retreat"] = 150,
				["Camp Taurajo"] = 90,
				["Zoram'gar Outpost"] = 231,
				["Brackenwall Village"] = 162,
				["Gadgetzan"] = 303,
				["Ratchet"] = 52,
				["Thunder Bluff"] = 182,
				["Valormok"] = 168,
				["Freewind Post"] = 184,
				["Splintertree Post"] = 162,
				["Orgrimmar"] = 142,
			},
			["Kargath"] = {
				["Undercity"] = 497,
				["Hammerfall"] = 263,
				["Thorium Point"] = 56,
				["Booty Bay"] = 417,
				["Stonard"] = 280,
				["Flame Crest"] = 87,
				["Grom'gol"] = 313,
			},
			["Bloodvenom Post"] = {
				["Crossroads"] = 241,
				["Orgrimmar"] = 259,
				["Splintertree Post"] = 333,
				["Thunder Bluff"] = 423,
				["Valormok"] = 241,
				["Everlook"] = 190,
				["Ratchet"] = 292,
				["Zoram'gar Outpost"] = 471,
			},
			["Sun Rock Retreat"] = {
				["Crossroads"] = 150,
				["Thunder Bluff"] = 175,
				["Zoram'gar Outpost"] = 380,
				["Splintertree Post"] = 311,
				["Orgrimmar"] = 290,
			},
			["Shadowprey Village"] = {
				["Brackenwall Village"] = 416,
				["Gadgetzan"] = 468,
				["Valormok"] = 447,
				["Thunder Bluff"] = 178,
				["Ratchet"] = 388,
				["Camp Taurajo"] = 265,
				["Orgrimmar"] = 385,
			},
			["Thorium Point"] = {
				["Stonard"] = 286,
				["Kargath"] = 70,
				["Undercity"] = 566,
				["Light's Hope Chapel"] = 559,
			},
			["Ratchet"] = {
				["Crossroads"] = 69,
				["Gadgetzan"] = 345,
				["Sun Rock Retreat"] = 218,
				["Shadowprey Village"] = 360,
				["Camp Taurajo"] = 158,
				["Zoram'gar Outpost"] = 299,
				["Brackenwall Village"] = 231,
				["Thunder Bluff"] = 250,
				["Orgrimmar"] = 210,
				["Camp Mojache"] = 320,
			},
			["Brackenwall Village"] = {
				["Crossroads"] = 162,
				["Gadgetzan"] = 222,
				["Thunder Bluff"] = 224,
				["Marshal's Refuge"] = 329,
				["Ratchet"] = 214,
				["Orgrimmar"] = 217,
			},
			["Revantusk Village"] = {
				["Undercity"] = 284,
				["Hammerfall"] = 93,
				["Booty Bay"] = 743,
				["Stonard"] = 631,
				["Tarren Mill"] = 159,
			},
			["Hammerfall"] = {
				["Revantusk Village"] = 91,
				["Kargath"] = 259,
				["Tarren Mill"] = 117,
				["Stonard"] = 539,
				["Flame Crest"] = 344,
				["Undercity"] = 259,
			},
			["Light's Hope Chapel"] = {
				["Undercity"] = 262,
			},
			["Booty Bay"] = {
				["Kargath"] = 406,
				["Hammerfall"] = 668,
				["Stonard"] = 267,
				["Thorium Point"] = 462,
				["Revantusk Village"] = 757,
				["Grom'gol"] = 102,
			},
			["The Sepulcher"] = {
				["Tarren Mill"] = 95,
				["Undercity"] = 112,
			},
			["Flame Crest"] = {
				["Booty Bay"] = 472,
				["Kargath"] = 99,
				["Stonard"] = 213,
				["Grom'gol"] = 401,
			},
			["Orgrimmar"] = {
				["Marshal's Refuge"] = 494,
				["Bloodvenom Post"] = 252,
				["Moonglade"] = 373,
				["Shadowprey Village"] = 385,
				["Ratchet"] = 161,
				["Brackenwall Village"] = 229,
				["Freewind Post"] = 294,
				["Gadgetzan"] = 417,
				["Camp Taurajo"] = 200,
				["Zoram'gar Outpost"] = 250,
				["Crossroads"] = 110,
				["Sun Rock Retreat"] = 260,
				["Valormok"] = 99,
				["Thunder Bluff"] = 224,
				["Everlook"] = 319,
				["Splintertree Post"] = 89,
				["Camp Mojache"] = 361,
			},
			["Everlook"] = {
				["Orgrimmar"] = 304,
				["Ratchet"] = 357,
				["Bloodvenom Post"] = 195,
				["Moonglade"] = 134,
			},
			["Undercity"] = {
				["Kargath"] = 488,
				["Hammerfall"] = 301,
				["Light's Hope Chapel"] = 261,
				["The Sepulcher"] = 106,
				["Tarren Mill"] = 141,
				["Revantusk Village"] = 284,
			},
			["Gadgetzan"] = {
				["Marshal's Refuge"] = 108,
				["Shadowprey Village"] = 463,
				["Ratchet"] = 331,
				["Orgrimmar"] = 350,
				["Brackenwall Village"] = 222,
				["Crossroads"] = 301,
				["Valormok"] = 448,
				["Thunder Bluff"] = 304,
				["Freewind Post"] = 87,
				["Camp Taurajo"] = 223,
				["Splintertree Post"] = 439,
				["Camp Mojache"] = 200,
			},
			["Freewind Post"] = {
				["Thunder Bluff"] = 225,
				["Ratchet"] = 245,
				["Sun Rock Retreat"] = 343,
				["Shadowprey Village"] = 323,
				["Camp Taurajo"] = 137,
				["Splintertree Post"] = 356,
				["Orgrimmar"] = 335,
			},
			["Thunder Bluff"] = {
				["Crossroads"] = 159,
				["Gadgetzan"] = 290,
				["Sun Rock Retreat"] = 182,
				["Shadowprey Village"] = 159,
				["Camp Taurajo"] = 87,
				["Zoram'gar Outpost"] = 389,
				["Brackenwall Village"] = 239,
				["Valormok"] = 269,
				["Freewind Post"] = 204,
				["Ratchet"] = 210,
				["Splintertree Post"] = 296,
				["Orgrimmar"] = 207,
			},
			["Nighthaven"] = {
				["Thunder Bluff"] = 543,
			},
			["Camp Taurajo"] = {
				["Crossroads"] = 79,
				["Thunder Bluff"] = 114,
				["Freewind Post"] = 125,
				["Ratchet"] = 130,
				["Orgrimmar"] = 221,
			},
			["Grom'gol"] = {
				["Kargath"] = 327,
				["Booty Bay"] = 81,
				["Stonard"] = 205,
				["Flame Crest"] = 402,
				["Tarren Mill"] = 704,
			},
			["Tarren Mill"] = {
				["Undercity"] = 139,
				["Hammerfall"] = 118,
				["The Sepulcher"] = 99,
				["Kargath"] = 376,
				["Revantusk Village"] = 195,
			},
			["Stonard"] = {
				["Undercity"] = 782,
				["Light's Hope Chapel"] = 774,
				["Tarren Mill"] = 663,
				["Grom'gol"] = 189,
				["Revantusk Village"] = 636,
				["Hammerfall"] = 547,
				["Booty Bay"] = 260,
				["Flame Crest"] = 197,
				["Kargath"] = 285,
			},
			["Zoram'gar Outpost"] = {
				["Crossroads"] = 228,
				["Sun Rock Retreat"] = 378,
				["Freewind Post"] = 412,
				["Thunder Bluff"] = 410,
				["Splintertree Post"] = 167,
				["Camp Taurajo"] = 318,
			},
			["Marshal's Refuge"] = {
				["Ratchet"] = 443,
				["Gadgetzan"] = 113,
				["Orgrimmar"] = 462,
			},
			["Valormok"] = {
				["Crossroads"] = 172,
				["Orgrimmar"] = 121,
				["Bloodvenom Post"] = 232,
				["Splintertree Post"] = 94,
				["Thunder Bluff"] = 257,
				["Zoram'gar Outpost"] = 253,
				["Ratchet"] = 223,
				["Camp Mojache"] = 423,
			},
			["Moonglade"] = {
				["Everlook"] = 142,
				["Ratchet"] = 404,
				["Orgrimmar"] = 370,
			},
			["Splintertree Post"] = {
				["Crossroads"] = 160,
				["Sun Rock Retreat"] = 310,
				["Thunder Bluff"] = 321,
				["Orgrimmar"] = 96,
				["Valormok"] = 96,
				["Zoram'gar Outpost"] = 166,
			},
			["Camp Mojache"] = {
				["Marshal's Refuge"] = 307,
				["Brackenwall Village"] = 421,
				["Gadgetzan"] = 201,
				["Crossroads"] = 263,
				["Thunder Bluff"] = 259,
				["Shadowprey Village"] = 201,
				["Ratchet"] = 315,
				["Orgrimmar"] = 406,
			},
		},
		["Alliance"] = {
			["Booty Bay"] = {
				["Nethergarde Keep"] = 266,
				["Stormwind"] = 220,
				["Darkshire"] = 175,
				["Sentinel Hill"] = 181,
			},
			["Refuge Pointe"] = {
				["Menethil Harbor"] = 126,
				["Ironforge"] = 271,
				["Aerie Peak"] = 72,
				["Thelsamar"] = 171,
				["Southshore"] = 86,
			},
			["Everlook"] = {
				["Talrendis Point"] = 176,
			},
			["Moonglade"] = {
				["Auberdine"] = 142,
			},
			["Talonbranch Glade"] = {
				["Everlook"] = 121,
			},
			["Thorium Point"] = {
				["Ironforge"] = 94,
				["Morgan's Vigil"] = 96,
			},
			["Auberdine"] = {
				["Rut'theran Village"] = 84,
				["Stonetalon Peak"] = 181,
				["Astranaar"] = 176,
				["Moonglade"] = 151,
				["Theramore"] = 675,
				["Nijel's Point"] = 291,
			},
			["Aerie Peak"] = {
				["Southshore"] = 68,
				["Chillwind Camp"] = 54,
				["Refuge Pointe"] = 75,
			},
			["Light's Hope Chapel"] = {
				["Ironforge"] = 369,
			},
			["Lakeshire"] = {
				["Stormwind"] = 113,
				["Thelsamar"] = 415,
				["Sentinel Hill"] = 133,
				["Darkshire"] = 60,
				["Menethil Harbor"] = 441,
			},
			["Morgan's Vigil"] = {
				["Stormwind"] = 151,
				["Thorium Point"] = 104,
				["Lakeshire"] = 64,
			},
			["Menethil Harbor"] = {
				["Stormwind"] = 261,
				["Thelsamar"] = 163,
				["Ironforge"] = 89,
				["Darkshire"] = 361,
				["Refuge Pointe"] = 113,
				["Southshore"] = 107,
			},
			["Ironforge"] = {
				["Stormwind"] = 210,
				["Darkshire"] = 312,
				["Thelsamar"] = 101,
				["Menethil Harbor"] = 128,
				["Refuge Pointe"] = 253,
				["Chillwind Camp"] = 294,
				["Southshore"] = 265,
			},
			["Theramore"] = {
				["Gadgetzan"] = 157,
				["Nijel's Point"] = 334,
				["Thalanaar"] = 162,
				["Auberdine"] = 620,
				["Ratchet"] = 115,
				["Rut'theran Village"] = 704,
			},
			["Chillwind Camp"] = {
				["Southshore"] = 85,
				["Aerie Peak"] = 66,
			},
			["Rut'theran Village"] = {
				["Auberdine"] = 86,
				["Astranaar"] = 261,
			},
			["Ratchet"] = {
				["Gadgetzan"] = 261,
				["Stonetalon Peak"] = 437,
				["Astranaar"] = 284,
				["Thalanaar"] = 268,
				["Theramore"] = 106,
				["Talrendis Point"] = 132,
			},
			["Thalanaar"] = {
				["Feathermoon"] = 179,
				["Theramore"] = 159,
				["Gadgetzan"] = 171,
			},
			["Gadgetzan"] = {
				["Talonbranch Glade"] = 670,
				["Ratchet"] = 262,
				["Theramore"] = 154,
				["Thalanaar"] = 177,
			},
			["Darkshire"] = {
				["Lakeshire"] = 60,
				["Sentinel Hill"] = 93,
				["Ironforge"] = 333,
				["Stormwind"] = 88,
				["Booty Bay"] = 171,
			},
			["Nethergarde Keep"] = {
				["Morgan's Vigil"] = 207,
				["Lakeshire"] = 150,
			},
			["Nighthaven"] = {
				["Rut'theran Village"] = 152,
			},
			["Thelsamar"] = {
				["Ironforge"] = 109,
				["Stormwind"] = 319,
				["Refuge Pointe"] = 164,
				["Menethil Harbor"] = 153,
			},
			["Talrendis Point"] = {
				["Ratchet"] = 135,
			},
			["Nijel's Point"] = {
				["Theramore"] = 308,
				["Gadgetzan"] = 464,
				["Stonetalon Peak"] = 120,
				["Astranaar"] = 273,
				["Ratchet"] = 422,
				["Feathermoon"] = 232,
				["Rut'theran Village"] = 367,
			},
			["Stormwind"] = {
				["Sentinel Hill"] = 78,
				["Lakeshire"] = 113,
				["Darkshire"] = 116,
				["Menethil Harbor"] = 343,
				["Booty Bay"] = 245,
				["Thelsamar"] = 317,
				["Ironforge"] = 259,
				["Southshore"] = 443,
			},
			["Stonetalon Peak"] = {
				["Auberdine"] = 177,
				["Astranaar"] = 154,
			},
			["Sentinel Hill"] = {
				["Lakeshire"] = 130,
				["Thelsamar"] = 389,
				["Booty Bay"] = 185,
				["Ironforge"] = 337,
				["Stormwind"] = 86,
				["Darkshire"] = 97,
			},
			["Astranaar"] = {
				["Auberdine"] = 148,
				["Rut'theran Village"] = 231,
			},
			["Cenarion Hold"] = {
				["Feathermoon"] = 175,
			},
			["Feathermoon"] = {
				["Thalanaar"] = 155,
				["Nijel's Point"] = 227,
			},
			["Southshore"] = {
				["Ironforge"] = 206,
				["Menethil Harbor"] = 110,
				["Refuge Pointe"] = 74,
			},
		},
	},
}
